### ISSUE TITLE
Document state should not be persisted

### ISSUE THREAD

**Issue by larvanitis** [evolus/pencil#105]
* Operating system: Linux
* Pencil version: 3.0.0-rc.1

The document state such as _last open page_ (should be first page), _page zoom_ per page (should be 100%) etc should not be saved, unless it is explicitly enabled in an option in program `Settings` or on a per document option.

**Comment by dgthanhan** [comment]
The default setting should be that state will be saved. This is how it is designed, not the other way around. Setting will be added to alllow users to change this behavior but the default value for this setting will be "Saved".

**Comment by larvanitis** [comment]
Thanks
