### ISSUE TITLE
Malware in 3.0.0-rc.1

### ISSUE THREAD

**Issue by RonR-WebDesign** [evolus/pencil#111]
* Operating system: Win 10
* Pencil version:  3.0.0-rc.1

Malware!  Windows Defender is reporting the existence of a Win32/Varpes variant: https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fVarpes.M!cl&threatid=2147708972&enterprise=0

Bummer, looks like cool new stuff...

**Comment by larvanitis** [comment]
Duplicate of #76

**Comment by RonR-WebDesign** [comment]
But...  there is no resolution!  Is there a new version?

**Comment by dgthanhan** [comment]
Please track the other reported issue #76 marked by @larvanitis. It's not necessary to leave this open as the issue was already reported and we are working on it.
