### ISSUE TITLE
How to compile from source?

### ISSUE THREAD

**Issue by dasj19** [evolus/pencil#113]
- Operating system: Debian unstable (sid)
- Pencil version: 3.0.0-rc1
  Hello I am trying to compile your software from source. I followed the instructions in the README file but I am unable to get your software running.
  What I have tried is: 

```
git clone https://github.com/electron/electron-quick-start
npm install
npm start
```

And the only thing that opens is a chromium browser displaying "Hello World! We are using node 6.3.0, Chromium 52.0.2743.82, and Electron 1.3.3."
How do I get electron to run your application? Thank you!
PS: I am trying to build a debian package and get it approved in the main distribution

**Comment by dgthanhan** [comment]
Please clone this repository instead of the electron quick start.

```
git clone https://github.com/evolus/pencil.git
```

**Comment by sTiKyt** [comment]
@dasj19 this repository seems outdated, please post your Issue to our fork! We'll updаte it soon!
https://github.com/DarkSecDevelopers/RePencil

**Comment by dasj19** [comment]
Time has passed and I no longer use debian, and my current distro has pencil packaged, so closing this issue.
