### ISSUE TITLE
Connector support for flowchart is broken

### ISSUE THREAD

**Issue by dgthanhan** [evolus/pencil#12]
Originally posted by @maxandersen
in pencil 2 you could drag the "ends" of lines to shapes and they would connect.
How do I do that in Pencil 3 ?

--

Comments by @v3ss0n:
trying to do that too, i guess i will take a look in code
I think connectors are not avliable in current Master yet.

**Comment by dgthanhan** [comment]
Comments by @v3ss0n:
Yes , i will submit an RFC for that.

**Comment by v3ss0n** [comment]
we have this fixed now?

**Comment by dgthanhan** [comment]
This is fixed and scheduled for 3.0.0-beta2

**Comment by v3ss0n** [comment]
thanks gonna give a try

**Comment by dgthanhan** [comment]
If you would like to try the code, make sure that you are in the 'development' branch. The new changes are still not merged into master.
