### ISSUE TITLE
Document treemodel should be able to show the contents of a parent page on child pages

### ISSUE THREAD

**Issue by sebastianfilke** [evolus/pencil#136]
* Operating system: ALL
* Pencil version: 3.0.0-rc.1

The tree model for the documents is a nice way to structure the documents for mockups, but this should definitely go a step further, otherwise the use case is not that useful.
If you have a parent page and one or more child pages there should be a way to show the contents of the parent/master page in fixed mode for a child page. so you can't edit, drag and drop the elements of the parent. it's like a background.
Normally you have a some contents on a page which repeats on all the other pages (a header with some user information, a footer, border around the page....). you always have to copy them on the other pages and if you have to make a change on this content, you have to edit all pages with this content.
If you have a master page the child pages should have an option to say if you want to show the content of the parent. this would be great, so you can edit the content for all pages in one time!
this feature would be nice and shouldn't be so hard to implement.

**Comment by dgthanhan** [comment]
The tree model is designed to represent the logical relationship among pages, not physical. If you want to do what you are describing, use the background page feature instead.

**Comment by sebastianfilke** [comment]
ah okay, i see that this feature already exists. this is a hidden feature!
