### ISSUE TITLE
Control key conflicts with right click on Mac

### ISSUE THREAD

**Issue by gdvine** [evolus/pencil#146]
* Operating system: OS X
* Pencil version: 3.0.0.rc1

Using control+click is a standard way to emulate right-click in OS X, so when doing control-key operations such as selecting multiple objects, the right-click menu comes up too, breaking the UX.

Possible solution: allow user to set the control-key mapping to a different key (such as command key in OS X) in settings.

**Comment by pnvananh** [comment]
Changed into using Cmd+Click on Mac.
