### ISSUE TITLE
What is the status of this software?

### ISSUE THREAD

**Issue by lassehp** [evolus/pencil#148]
* Operating system: Ubuntu
* Pencil version:

I just found Pencil, but the project website seems rather out of date, and the download links don't work.

Is this software still actively developed and supported?

**Comment by Madmarsu** [comment]
Also interested in the answer… This tool is a very good alternative to gl*ffy or b*lsamiq.
If the 3.0 could become a stable release that would be great.
Do you need help on that?

**Comment by mcmamcma** [comment]
I am also interested in the answer. I used the 3.0 RC1 version with ubuntu 16.04 to make 1 mockup and didn't find any instability. Great tool.

**Comment by dgthanhan** [comment]
The team is working on addressing some minor cross-platform usability issues and also on experimenting the NSIS-based installer for Windows to solve the false positive malware alarm. We expecting the 3.0 release to be ready in the upcoming weeks.
