### ISSUE TITLE
Multiselect doesn't work using shift-click

### ISSUE THREAD

**Issue by tmmls** [evolus/pencil#169]
Hi,

With this post I would like to report a bug.

Selecting multiple elements by click and dragging around the elements works perfectly.
However, selecting multiple elements by using shift-click on each individual element doesn't work.
- Operating system: Ubuntu 14.0.4 LTS
- Pencil version: 3.0.0

**Comment by sanstream** [comment]
Have you tried using Ctrl instead?

**Comment by bes1002t** [comment]
Yes ctrl + click is working but imho this is not common. In most programs the multi select is working with shift + click.
