### ISSUE TITLE
New Pencil UI is not dense enough

### ISSUE THREAD

**Issue by jandsu** [evolus/pencil#173]
- Operating system: Irrelevant
- Pencil version: 3.0.0-rc.1

It is certainly a matter of taste, so excuse me for this kind of bug... which is typical of a Pencil user who is by definition focused on UX :)

IMHO, the new UI looks good but is could be more efficient. If you have to design a mobile app it's fine but if you need to design a desktop UI from a desktop which does not have a 4K screen, your design does not easily fit into the screen.

In particular, I believe that
1. the top zone (burger menu and toolbars) is huge...
2. the leftmost tabs (clipart/my shapes/shapes) are not worth their size
3. all this components panel _seems_ much bigger than in 2.0.5 (it is not actually, but there is some room for improvement).

Anyway, thanks for this _very_ useful application!

**Comment by monkeydri** [comment]
👍 

I work on my laptop most of the time (11" screen), and here is how Pencil looks in full screen :

![screen shot 2016-11-03 at 4 06 52 pm](https://cloud.githubusercontent.com/assets/18724661/19971521/93723b32-a1df-11e6-9582-90050b4c84b6.png)

So much vertical space wasted ! It would be nice if the "top zone" (as @jandsu described it) could be trimmed (with arrow to access additional elements). I don't really like this kind of arrow (it adds another click) but I'd rather have one than so much space wasted. Another possibility would be foldable panels, I found that quite handy in many apps once we get used to it.

Pencil Version : 3.0.0-rc.1
OS : macOS 10.12

**Comment by LeadManPL** [comment]
* Operating system: Ubuntu 16.04 
* Pencil version: 3.0.4
UI is still poorly designed, and wastes a lot of space to work on.

**Comment by monkeydri** [comment]
It looks good on Ubuntu 17.10 (gnome-shell 3.26, wayland), same pencil version (3.0.4), can you show some screenshots ?

**Comment by jandsu** [comment]
I would be surprised if it has anything to do with Gnome as it is based on Electron (hence Chromium under the hood).
Anyway, I tested it again and it seems to be fixed now: there are some nice rules to shrink the top zone (with the burgerr-menu etc...) when the app is shrinking....
For me, we can close this issue now... if anyone disagrees, I guess he should file another issue.

**Comment by jandsu** [comment]
BTW... tested on Ubuntu 16.04 & Pencil 3.0.4
