### ISSUE TITLE
Properties window prevents adding new shapes

### ISSUE THREAD

**Issue by shellstrom** [evolus/pencil#175]
- Operating system: Mac OS X - El Capitan
- Pencil version: 2.0.6

1: Add a new shape to the canvas
2: Right-click on the shape
3: Select Properties
4: Select a color
5: Click Apply
6: Add a new shape

_Expected result_
A new shape gets added

_Actual result_
The new shape blinks into view and then disappears, not adding the shape to the canvas

_Findings and comments_
- The Properties window for the first shape prevents a new addition of another shape

_Suggestion_
- Mimic the behaviour of Mac OS, which apply effects immediately, such as a colour change, without having to click apply, and remove the "Close" and "Apply" buttons, or
- Mimic Windows behaviour, and add an additional button "Ok", which applies and closes the window
- [A third possible suggestion, feel free to share any ideas]

**Comment by dgthanhan** [comment]
This workspace is for 3.x version of Pencil. 2.0.x is no longer supported.
