### ISSUE TITLE
Will you plan to create package for i386?

### ISSUE THREAD

**Issue by nemelnikov** [evolus/pencil#200]
Question is the same - Will you plan to create package for i386?

dpkg: error processing archive Pencil-3.0.0-rc.1.deb (--install):
 package architecture (amd64) does not match system (i386)
Errors were encountered while processing:
 Pencil-3.0.0-rc.1.deb

**Comment by dgthanhan** [comment]
Yes, this planned. RC2 release will include 32-bit packages for all platforms except Mac.
