### ISSUE TITLE
Export as PDF with filename test.com will create an EXE

### ISSUE THREAD

**Issue by shyamdadimuni** [evolus/pencil#203]
When I export my work to PDF and save with "test.com" will create an EXE instead PDF.

* Operating system: Windows 10
* Pencil version: 3.0.0 -rc.1

**Comment by dgthanhan** [comment]
Why you named the file that way in the first place?
In Windows, both .com and .exe are considered executable.
Pencil won't try to change the actual file name the user wants to use.
