### ISSUE TITLE
Downloadlink to Ubuntu Versions broken, Missing Link to Github Releases

### ISSUE THREAD

**Issue by pixelbrackets** [evolus/pencil#217]
* Operating system: Ubuntu 16.04
* Pencil version: 3.0.0-rc.1

Hey guys,

on the current homepage the downloadlink to ubuntu versions is broken:
http://pencil.evolus.vn/ → http://pencil.evolus.vn/dl/evoluspencil_2.0.5_all.deb leads to a 404

Also: I miss prominent links to the github page → to show new releases and to encourage people to contribute.

PS: Version 3.0.0-rc1 works like a charm. Is there a roadmap when this branch is gonne be released as stable version?

**Comment by dgthanhan** [comment]
Link are fixed now,
