### ISSUE TITLE
Printing more than once Hangs on "Exporting" screen

### ISSUE THREAD

**Issue by datapharmer** [evolus/pencil#227]
* Operating system: Windows 10 Pro
* Pencil version: Pencil 3.0.0 - RC1

To reproduce:
1. Create or Open a Pencil Document
2. Choose Menu > Print and set paper size to "Letter" click print, choose a printer and ok
3. After printing choose Menu > Print and set paper size to "Letter" click print
Expected Behavior: Prints
Actual Behavior: Export screen pops up and hangs
Workaround: Exit program completely and reload every time you need to print (very annoying!)

Printers tested against: HP 8600 inkjet, Canon m620 Laser, Microsoft Print to PDF

![image](https://cloud.githubusercontent.com/assets/6548767/21851224/14933b94-d7dc-11e6-9804-a72b666c06aa.png)

**Comment by DaveKlassen4** [comment]
I have just seen this as well, except the first time it prints, it does not complete the full job (XML data is printed on Page 7 and the remainder of the pages are truncated.).

**Comment by fkleedorfer** [comment]
Same issue as @datapharmer  with version 3.0.4, A4  paper and Ricoh printer.

**Comment by DaveKlassen** [comment]
I found the best results by exporting to the file type I wanted, and then using another program to print the data in that format.

**Comment by Blackzeus** [comment]
Same issue as @datapharmer with version 3.0.4 on win 10 Home, A3 paper and Ricoh printer.
As @DaveKlassen suggested, it is best to export the pages as *.png and then print them by using the print entry from the context menu.

**Comment by karbonfybar** [comment]
I have found this same issue with ver 3.0.4 on Mac OS X 10.13.2/10.12. Print once, restart, repeat.
Also, after printing once, I tried exporting and it hung as well. After restarting pencil, I was able to export, successfully, a number of different files. This is a suitable workaround for me, but the printing issue should still be fixed.
