### ISSUE TITLE
Scaling issue on Windows 10 at 3840 x 2160 with 3.0.0 beta 1

### ISSUE THREAD

**Issue by joaobarcia** [evolus/pencil#23]
Hi there,

Pencil is not scaling properly on Windows 10 at 3840 x 2160 with 3.0.0 beta 1. To be able to use a 3480 x 2160 15'' inch monitor, you need to scale things up quite a bit. Usually I have my Windows set for 225%.

![pencil issue - windows scaling 225](https://cloud.githubusercontent.com/assets/6717014/15863481/0f8910d6-2ccb-11e6-9431-061352d167ad.PNG)

This makes most programs display regularly, but Pencil looks like this:

![pencil issue - scaling 225](https://cloud.githubusercontent.com/assets/6717014/15863513/34f04db2-2ccb-11e6-9a9b-8500aef2d5d5.PNG)

If I bring scaling back to 100%, most programs become unusable:

![pencil issue - windows scaling 100](https://cloud.githubusercontent.com/assets/6717014/15863534/443e3c16-2ccb-11e6-9423-89ad66cb0510.PNG)

But Pencil displays regularly:

![pencil issue - scaling 100](https://cloud.githubusercontent.com/assets/6717014/15863541/4f22d09c-2ccb-11e6-878c-84a2ebb9f2f3.PNG)

Cheers

**Comment by dgthanhan** [comment]
It's unfortunately that we don't have such a high density screen here for testing but I guess that it was the problem of incorrect calculation of system font size inside Pencil.

Could you please do us a favor by making another screenshot having both Pencil and the Windows File Explorer runing side by side at the scale of 225% (where the Windows File Explorer is usable) so that we can compare?

**Comment by joaobarcia** [comment]
Hi, hope it helps
![pencil issue - file explorer and pencil](https://cloud.githubusercontent.com/assets/6717014/15867160/cc38c38a-2cd9-11e6-96d6-d392dad9b022.PNG)

**Comment by ab014** [comment]
I am having a similar scaling error on elementaryOS (based on Ubuntu 14.04) at 1366 x 768.
![screenshot from 2016-07-02 20 28 32](https://cloud.githubusercontent.com/assets/16028868/16540933/950e2b70-4093-11e6-8a2e-95f40c1c12c6.png)
