### ISSUE TITLE
[Help] How to resize a container without rezing the elements inside

### ISSUE THREAD

**Issue by TioNoob** [evolus/pencil#231]
* Operating system: Windows 7
* Pencil version: 2.0.5

I've searched on the internet but didn't find any anwser.

I have the following situation:

This is the element at normal size:
![1](https://cloud.githubusercontent.com/assets/5540088/22112813/858d97b6-de4b-11e6-9d4a-1ffbcceb76c9.JPG)

I want to resize it like this:
![3](https://cloud.githubusercontent.com/assets/5540088/22113087/52016a2a-de4c-11e6-8041-8dc4c747fd1d.JPG)

But, all I get is:
![2](https://cloud.githubusercontent.com/assets/5540088/22112844/9ce2acee-de4b-11e6-8797-4aeb67ade59a.JPG)

I've tried to use the Sizing Policy, but can't figure out how to use it properly.
And the documentation isn't that good about this feature.

There is a way to achieve this result ?

*Sorry if here isn't the right place to post this kind of doubt*

**Comment by dgthanhan** [comment]
Is this something you created by grouping a text input shape with a magnifier icon shape?
If that is the case, try setting the magnifier icon sizing policy to:
Width and Height: Locked (first option) - as you don't want to change its size proportionally to the parent.
Horizontal: Locked to the right (3rd option) - as you want it to stick to the right side.
Vertical: Locked to the middle (2nd option) - as you want it to same vertically aligned with the parent.

The upcoming version of Pencil will have a built-in n-patch shape to allow you define a scaling model for even a bitmap image.

**Comment by TioNoob** [comment]
Great, thanks for the help.

It worked like a charm.
