### ISSUE TITLE
Can't drag and drop components

### ISSUE THREAD

**Issue by dan-passaro** [evolus/pencil#266]
* Operating system: Ubuntu 16.04, Gnome 3
* Pencil version: 2.0.5

I can't drag and drop any components. Starting the app and trying to drag a 'Rectangle' onto 'Untitled Page' does nothing. The rectangle doesn't appear under my cursor at any point. It's like the tool is simply not responding to being clicked on. It does change color when I hover over it with my mouse, and other menus and toolbar buttons work normally.

**Comment by quiznilo1** [comment]
I can confirm.

Operating System: Funtoo x86-64bit, gcc-5.3.0, glibc-2.22
Pencil version: 2.0.5

Some debug spammage from console:
1488134652331	addons.manager	WARN	Error in background update: [Exception... "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIPrefBranch.getBoolPref]"  nsresult: "0x8000ffff (NS_ERROR_UNEXPECTED)"  location: "JS frame :: resource://gre/modules/AddonManager.jsm :: AddonManagerInternal.backgroundUpdateCheck/buPromise< :: line 1436"  data: no] Stack trace: AddonManagerInternal.backgroundUpdateCheck/buPromise<()@resource://gre/modules/AddonManager.jsm:1436 < TaskImpl_run()@resource://gre/modules/Task.jsm:319 < TaskImpl()@resource://gre/modules/Task.jsm:280 < createAsyncFunction/asyncFunction()@resource://gre/modules/Task.jsm:254 < Task_spawn()@resource://gre/modules/Task.jsm:168 < AddonManagerInternal.backgroundUpdateCheck()@resource://gre/modules/AddonManager.jsm:1433 < backgroundUpdateTimerHandler()@resource://gre/modules/AddonManager.jsm:3046 < amManager.prototype.notify()@resource://gre/components/addonManager.js:164 < TM_notify/<()@resource://gre/components/nsUpdateTimerManager.js:201 < TM_notify()@resource://gre/components/nsUpdateTimerManager.js:249

**Comment by zbam** [comment]
Same issue here with Linux Mint 18.1

**Comment by ggramlich** [comment]
It probably has to do with the Firefox version.
See
https://github.com/prikhi/pencil/issues/850
https://github.com/prikhi/pencil/issues/312

I installed palemoon https://www.palemoon.org/ and changed the start script of pencil to use palemoon instead of firefox.

But because of
https://github.com/samuell/evoluspencil/issues/682

I switched to Version 3 RC2

**Comment by dgthanhan** [comment]
We shifted the focus into 3.0 and 2.0.5 issues won't be addressed.
