### ISSUE TITLE
Pencil 3.0 RC2 Cant open 2.0.5 projects, and fonts are not great

### ISSUE THREAD

**Issue by johnvlittle** [evolus/pencil#268]
* Operating system: win 10 64 bit pro
* Pencil version: 3.0 RC2
As I cant use pencil 2.0.5 as all text items always load blank, I tried 3.0 RC2.
It wont load any of the ep files I created in 2.0.5, just says "something went wrong"
Also, the fonts are difficult to read on my 30" monitor with 125% scaling.  
Subjectively, I prefer the UI of 2.0.5 than 3.  3 feels like a mobile product.
The shape browser in 3.0 is much less efficiuent use of space, there is so much wasted blank space, and you see less shapes on a decent monitor at least.

**Comment by bmix** [comment]
Agree with all points! I have the same problem with 2.0.5 on Windows 10-64-Home (text loads blank), this is why I switched to 3-rc2. I also can not load my previous projects. I get the "unexpected error" mentioned by @johnvlittle. 
And I also prefer the UI of 2.0.5. It's classical, functional and very, very slick. A breeze to use! One of the most intuitive and elegant programs I ever used in my 34 years of computing. I find the shape browser uses too much screen-estate and the same goes for the toolbar at the top. The icons are too small in the toolbar and the padding at the bottom of the toolbar is too wide. I am on a 22" screen.

**Comment by dgthanhan** [comment]
Version 3.0 is expected to support .ep loading. If it's possible, please forward an 2.0.5 .ep file that you could not use in 3.0 and we can check what went wrong.
For the text font problem, there is an option in the settings to adjust font scaling, please try that and see if it helps. A screenshot may also help.

**Comment by johnvlittle** [comment]
Hi, could you give me an email address to send my non-opening ep files.

 

Thanks,

 

Simon.

**Comment by dgthanhan** [comment]
@johnvlittle feel free to forward the file to an.duong -at- evolus . vn.

**Comment by bmix** [comment]
For some reasons, this form does not allow uploads of ZIP archives, though it says, they would be supported. I zipped an *.ep file, that doesn't load and wanted to upload it, but I get the error:

> We don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.

**Comment by dgthanhan** [comment]
Latest code in 'development' branch has the loading error fixed. Please note one important point that the Native UI stencil is no longer supported, your .ep can be loaded but elements in those collection won't be rendered correctly.

**Comment by johnvlittle** [comment]
Unfortunately, I have only used native UI stencil elements.  It is the only one which looks like what we are building for.  So effectively, none of our 2.0.5 ep projects will work in 3.    Is there a plan to support native UI in a future version?  Currently, none of the text renders in 2.0.5.  It is practicle to go back to a pervious version to get the text back, and we will skip version 3?

 

It’s such a same, 2.0.5 is absolutely perfect except for the text not showing problem.  From what we have seen the UI for 3 is a step backwards (for desktop users at least).

 

Thanks,

**Comment by dgthanhan** [comment]
There is no plan for supporting the Native UI in the future. Pencil 2.0.5 Native UI support relies completely on Mozilla XUL which will be broken soon as Mozilla will remove XUL support and current XUL implementation may not work well with future desktop environment releases.
