### ISSUE TITLE
App locks on save

### ISSUE THREAD

**Issue by wender1** [evolus/pencil#271]
* Operating system: windows 7
* Pencil version: 3.0.0 RC2

The app very often freezes on save.

**Comment by LupusUmbrae** [comment]
Been seeing this myself.. had a quite look at the debug console and paused the application, seems to get stuck in [ColorSelector.prototype.initializeGridSelector](https://github.com/evolus/pencil/blob/v3.0.0-rc.2/app/views/editors/ColorSelector.js#L331)

It never entered the if statement until i manually changed the `colors` variable manually. I also can't see any worker threads so can only assume the application is stuck here just not sure why

When it happens again will pause it and add another comment (especially if its stuck somewhere else)

**Comment by LupusUmbrae** [comment]
happened again getting stuck in the same function

**Comment by dgthanhan** [comment]
@LupusUmbrae This has nothing to do with the ColorSelector. The saving error happens when there are problem with the underlying compression worker that creates the gzip file. Latest code has these implementations improved, please re-visit the cases and re-open this issue if it still happens.
