### ISSUE TITLE
Error opening file .epgz on Windows that was created on Linux

### ISSUE THREAD

**Issue by alvaropag** [evolus/pencil#272]
* Operating system: Windows 7 32bits, Kubuntu 16.10 64bits
* Pencil version: 3-rc2
A .epgz file was created on Linux and send via mail to a Windows PC, the file was opened, modified, saved and sent back for the Linux machine, were it didn`t open anymore. The error message only says  "unexpected error while acessing file: telas.epgz".
If the file is saved with .epz extensions it opens without problem.

**Comment by dgthanhan** [comment]
This issue is fixed in the latest 'development' code. Nightly builds are also available at http://pencil.evolus.vn/Nightly.html

**Comment by alessandroalb** [comment]
HI !
Have same similar problem.
Use pencil on Ubuntu Gnome 16.04 64 bit.
Save project on smb share on nas.
No problem until today.
Now i try to open one project, from smb share, i receive error : "unexpected error while accessing file: myproject.epgz".
Install upgrade pencil to Nightly **pencil_3.0.1.20170411003001_amd64.deb**.
Try now but nothing, some second i see it work, then stop.
Try to copy project on local hard disk and then open from it, but nothing, some second i see it work, then stop.
Ahi ahi, i rewrite my project, my time is not infinite.
Take time to solution.
By
