### ISSUE TITLE
p:lockH and p:lockW don't appear to work

### ISSUE THREAD

**Issue by dainbrump** [evolus/pencil#277]
* Operating system: Linux
* Pencil version: 3.0.0-rc2

According to [the tutorial docs](http://pencil-prototyping.readthedocs.io/projects/evolus-pencil/en/develop/stencil-dev/tutorial/dimensionshandleconstraints.html), adding ```p:lockH="true"``` should prevent height scaling. This does not appear to be working. My object renders with all handles draggable.

```
<Properties>
  <PropertyGroup name="Block Settings">
    <Property name="box" type="Dimension" p:lockH="true">98,36</Property>
```

Then, in the Behaviors I have:

```
      <For ref="block">
        <Box>$box</Box>
        <Fill>$fillColor</Fill>
      </For>
```

And in my p:Content I have:

```
<rect id="block" rx="2px" ry="2px" />
```

The block shows and all other properties seem to render just fine but I can change the height when I shouldn't be able to. Unless I read something wrong.

**Comment by dgthanhan** [comment]
The meta names are `p:lockHeight` and `p:lockWidth`. The provided documentation is not for Pencil V3.

**Comment by dainbrump** [comment]
Is there somewhere this information is available? I would have poked through the schema but I was unable to locate that.
