### ISSUE TITLE
Save from Windows not compatible with Linux (3.0.0-rc2)

### ISSUE THREAD

**Issue by 10robinho** [evolus/pencil#278]
* Operating system: Win10 / Ubuntu 16.04.01 LTS
* Pencil version: 3.0.0-rc2

It's simple. Yesterday I made something on my Windows PC and saved it to Drive. This morning I tried to open it in same version just on Linux machine and I got error 

> Unexpected error while accessing file: something.epgz

I don't know how can I debug more but I'm willing to help.

**Comment by 10robinho** [comment]
I found out that there is a console so I got more information.

Looks like save from windows is having problems with extracting itself to `/tmp/tmp-xxxxxxxxxxxx`.
It forget's to set permissions to `700` but it sets to `666` which results with unable to access folder error before it even extracts itself.

Now I'll try to find it in the code but I'm not sure that I'll be successful there.
I think there are enough information for developers to fix it now.

**Comment by dgthanhan** [comment]
Duplicated with #272
