### ISSUE TITLE
File not open .epgz

### ISSUE THREAD

**Issue by fdurmus77** [evolus/pencil#295]
* Operating system: Debian 8
* Pencil version: pencil_3.0.1.20170329003001_amd64.deb

**Comment by TioNoob** [comment]
Sorry, but what is the problem ?

I'm just seeing:

> Operating system: Debian 8
> Pencil version: pencil_3.0.1.20170329003001_amd64.deb

**Comment by sebastianfilke** [comment]
The same under Windows 8.1 and 10. Pencil opens but, doesn't load the mockup anymore.
With version 3.0.0 the files open correctly. This bug #77 correlates with this one.

**Comment by kirlat** [comment]
Second to that. Does not work for me with Pencil 3.0.2 on Windows 10.

**Comment by JohnSheppard** [comment]
Hello, third to that...Pencil 3.04, does not open a file directly from windows explorer. Would be really advantagous if it could.

**Comment by fdurmus77** [comment]
> Hello, third to that...Pencil 3.04, does not open a file directly from windows explorer. Would be really advantagous if it could.

Ok. But pencil_3.0.1 Application could not open this file.
