### ISSUE TITLE
Difference between epz and epgz file formats

### ISSUE THREAD

**Issue by Otiel** [evolus/pencil#298]
* Operating system: Windows 7 64bit
* Pencil version: 3.0.1

What is the difference between the epz and the epgz file formats? Both formats seem to be compressing at the same ratio. When saving a project to file, which one should I use?

**Comment by dgthanhan** [comment]
EPZ uses ZIP compression while EPGZ uses zlib compression. We recommend the EPGZ as it uses the built-in native zlib supports from Node.

**Comment by Otiel** [comment]
I see, thanks!
