### ISSUE TITLE
[Feature request] - make default fonts parametric

### ISSUE THREAD

**Issue by spilja** [evolus/pencil#306]
* Operating system: Windows 10
* Pencil version: 3.0.1

Please make default fonts parametric, it's terrible having to constantly manually switch from Comic Sans.

**Comment by dgthanhan** [comment]
Could you please more specific? I'm not sure where in the app Comic Sans is being used.

**Comment by spilja** [comment]
Sorry, sure. When you use Desktop Sketchy - GUI and choose an element such as Box, the label uses Comic Sans by default. Same thing goes for Text Field, Button, etc.

**Comment by dgthanhan** [comment]
Thanks for the details.
At the top-right corner of the collection pane when a collection is selected, there will be a button with a cog icon which allow you to set the default properties of shapes. The sketchty collection has its font configurable.

**Comment by spilja** [comment]
Ahh, thank you! :) 👍
