### ISSUE TITLE
[Feature Request] Import and Export: Sketch, Balsamiq and PSD files

### ISSUE THREAD

**Issue by mobesa** [evolus/pencil#309]
That would be so great to have if you're someone who works with other designers who have high-end software like these and need to exchange designs with them.

**Comment by pedrohidalgo** [comment]
+1 I think this is a very important feature. For me the Sketch one would be more important, would be really helpful to be able to download sketch sources from here: https://www.sketchappsources.com and be able to import them on Pencil

**Comment by dgthanhan** [comment]
We're not going to support sketch or any other proprietary software formats. Those formats are not documented, not open for use and supporting that even in a kind of reverse engineering just make it worse for the opensource community. Let's those live in there close caves. Pencil is not about free as in free beer. We encourage the free in free speech, we encourage the openess.

Don't try to post anything related to those here. It's really annoying when someone try to use the word 'source' for something that is just resource.

No, the answer is not.
