### ISSUE TITLE
Feature Request: Ability to dynamically adjust canvas size 

### ISSUE THREAD

**Issue by randyyaj** [evolus/pencil#315]
* Operating system: Mac
* Pencil version: Latest
Have the ability to specify width and height of canvas. I see the fit to canvas and padding but it would be nice to manually specify it somewhere in the toolbar and/or on new project.

**Comment by dgthanhan** [comment]
Right click on the page name and select "Properties...".

**Comment by randyyaj** [comment]
Ah thanks I missed that.
