### ISSUE TITLE
Cannot open file

### ISSUE THREAD

**Issue by ewezel** [evolus/pencil#325]
* Operating system: Windows 10
* Pencil version: 3.0.1

I got an error when I try to open my file, it is corrupt. Can you repair it?
https://1drv.ms/u/s!AiBcuAR-B2cUgqoKrgLYZJq-8HlfQQ

kind regards,

Erwin van Wezel

**Comment by dgthanhan** [comment]
I got your file repaired. It looks like the reference to one of your local file make the saving failed. Please upgrade to 3.0.2 and give me your email so that I can send the file back.

**Comment by ewezel** [comment]
Thx,

 

Erwin@vwzl.nl

 

Van: Dương Thành An [mailto:notifications@github.com] 
Verzonden: maandag 22 mei 2017 18:10
Aan: evolus/pencil <pencil@noreply.github.com>
CC: ewezel <erwin@vwzl.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [evolus/pencil] Cannot open file (#325)

 

I got your file repaired. It looks like the reference to one of your local file make the saving failed. Please upgrade to 3.0.2 and give me your email so that I can send the file back.
