### ISSUE TITLE
GitHub Releases page missing platform-specific builds?

### ISSUE THREAD

**Issue by movermeyer** [evolus/pencil#328]
Ever since 3.0.0, [the releases page](https://github.com/evolus/pencil/releases) is missing platform-specific builds.

The builds are still happening, since I can still download [platform-specific nightly builds](http://pencil.evolus.vn/Nightly.html).

However, I'd like to install 3.0.2 on Windows without having to build it myself. Perhaps there is something I'm missing?

* Operating system: Windows, etc.
* Pencil version: 3.0.0+

**Comment by dgthanhan** [comment]
Github for Pencil is the place for collaborating developer and contributors to the project. End user builds are definitely not listed here. The official download is at the website.
If you could get to the nightly build page, try looking up the nagivation bar, the dowload link is there.

**Comment by movermeyer** [comment]
Ah, I was looking at http://pencil.evolus.vn/Next.html, which is what I had saved as a bookmark.

Perhaps it's time to make that page redirect?

**Comment by movermeyer** [comment]
I disagree with idea that end user builds should only be on your website.

For example, there does not appear to be any way to access previous end user builds. This got in my way yesterday, where I was trying to help reproduce a problem, but I didn't have the same version that they did. If previous builds were readily available, I would have taken the extra step to test using both their version and the latest version.

**Comment by dgthanhan** [comment]
We will try to have a download archive in the website and yes, the download will be only there.
