### ISSUE TITLE
Official downloads are served over HTTP, not HTTPS

### ISSUE THREAD

**Issue by movermeyer** [evolus/pencil#334]
The [official download page](http://pencil.evolus.vn/Downloads.html) is being served over HTTP (not HTTPS), with no other way to verify the integrity of the site, nor the packages themselves.

We have seen in recent years nation states [modifying the content of webpages and downloads on the wire](https://threatpost.com/github-attack-perpetrated-by-chinas-great-cannon-traffic-injection-tool/112109/).

TLS (ie. SSL) encrypts the connection to the user to prevent these sorts of attacks. It would not only protect the download links and other content of your website being modified, but also secure the integrity of the download files themselves.

These days, there are free options for TLS certificates. An excellent example is https://letsencrypt.org/

Evolus' website and downloads should be served over TLS.

P.S: On top of TLS, projects also sign their end user packages so users can have confidence that the integrity of the downloaded files is maintained, even in the case of compromise of their webserver.

**Comment by dgthanhan** [comment]
If you want HTTPS, switch to HTTPS, it is there already. We just don't want to redirect for now.
