### ISSUE TITLE
I can't see the menu bar on Ubuntu Unity 16.04

### ISSUE THREAD

**Issue by juanibrex** [evolus/pencil#336]
* Operating system: Ubuntu 16.04 - Unity
* Pencil version: 3.0.2

Hey, I can't see the menu bar on Ubuntu Unity 16.04. 
I want to install some stencils but i can't because i don't see the menu `Tools > Install new collection...`.

Thanks

**Comment by dgthanhan** [comment]
Did you see the hamburger icon at the top-left corner?

**Comment by juanibrex** [comment]
Yes, I use it. But I think it's incomplete.
I took a screenshot to see that some functions are missing

![pencil-menu](https://cloud.githubusercontent.com/assets/175282/26766721/7f0a5bbc-496d-11e7-8b7c-819ddcf294d2.png)

**Comment by dgthanhan** [comment]
Click on the Manage Collections. It won't hurt.

**Comment by juanibrex** [comment]
Thanks dgthanhan, but the Manage Collections only show me the list of collections installed in Pencil right now, and my goal is install new collections.

**Comment by dgthanhan** [comment]
Font size on your system seem to be to large and makes Pencil did a wrong calculation. As a workaround, go to Settings and set a text scale smaller than 100%, restart Pencil and see if you have the "Install ..." buttons at the bottom of the collection management dialog.

**Comment by juanibrex** [comment]
Thank you very much!!!!
It's that! two day with that bug and this is the solution... Thanks again dgthanhan!

**Comment by dgthanhan** [comment]
Thanks @juanibrex
