### ISSUE TITLE
App crashes when opening installed stencil

### ISSUE THREAD

**Issue by mechatronik** [evolus/pencil#35]
* Operating system: Fedora 24 beta
* Pencil version: 3.0.0 beta 2

When opening Material Icons (v2.0.0) stencil installed from repository the program's window goes all white. When installing from file the problem is the same.

**Comment by sanstream** [comment]
You get the same effect after you close and start Pencil again. Possibly because the app remembers the the Material Icons collection as the last one used: 

``` config.json
"Collection.lastUsedCollection.id": "nz.nwatson.MaterialIcons",
```
When I change it to this:
``` config.json
"Collection.lastUsedCollection.id": "Evolus.Sketchy.GUI",
```
Pencil starts without any problems.
