### ISSUE TITLE
Images Gone when epz reopened

### ISSUE THREAD

**Issue by NamelessBlank** [evolus/pencil#369]
* Operating system: windows 10
* Pencil version: 2.0.5

All images are gone after reopening Pencil app. :( Lot's of work needs to be recreated.

**Comment by dgthanhan** [comment]
We are no longer supporting the 2.x version. Please consider migrating to 3.x.

**Comment by NamelessBlank** [comment]
Hello dgthanhan, 

I installed version 3 and successfully recovered my project.  Thank You.
