### ISSUE TITLE
Wrapping text fields.

### ISSUE THREAD

**Issue by kennethalong** [evolus/pencil#38]
* Operating system: Windows 8
* Pencil version: 3.0
Is there a way to get text fields to wrap within a restrained rectangular area?  I only get my text displayed as a single line.  Am I doing something wrong?

**Comment by AlessioCorridori** [comment]
The text on the shape "Text Field" seems to be displayed in just one line. 
But you can use the "Box" shape (from Sketchy GUI for example), double click to insert the text and press CTRL + ENTER to create new lines while editing the text.
From the properties panel you can control the alignment and obtain basically a textbox with a multiline text restrained inside. This is how I usually do.
Hope this help you.

**Comment by kennethalong** [comment]
CTRL + ENTER isn't working for me.

**Comment by mbrainiac** [comment]
@kennethalong 

Use Rich Text from Common Shapes with 'Fixed Width' selected.
SHIFT + ENTER to create new lines.

**Comment by AlessioCorridori** [comment]
@kennethalong 
As @mbrainiac says, it's SHIFT + ENTER, my mistake...

**Comment by jekuno** [comment]
There's an issue with this though, see #39
