### ISSUE TITLE
Linking to external pages

### ISSUE THREAD

**Issue by yogeshkumarbalu** [evolus/pencil#383]
* Operating system: windows 7
* Pencil version: 3.0.4
I am trying to make an application prototype in pencil and please let me know how to make links to external pages. 

For example to - www.google.com from my prototype in pencil

**Comment by july8six** [comment]
Pencil does not allow linking to outside sources within the application.  It is not really a program for creating prototypes, it is for UX/UI design.

To link to a page inside the app do the following:
1. Create the page you want to link to
2. Right click on the element you want to use as an anchor element
3.  Click on the option that says link to
4.  Click on the page you wish to link to
