### ISSUE TITLE
Duplicate line breaks in exported PDF

### ISSUE THREAD

**Issue by jekuno** [evolus/pencil#39]
* Operating system: Mac OSX
* Pencil version: 3.0.0.-beta2

How to reproduce:
Add a HTML Text item (from Desktop Sketchy GUI). Insert multiline text (inserting linebreaks using Shift+Enter). Export as PDF.

The eported PDF contains blank lines (i.e. two line breaks) where there shouldn't be blank lines (but only a single linke break).

**Comment by dgthanhan** [comment]
This issue is confirmed.
The root cause was the the incorrect behavior of Webkit in transforming the `<br/>` tag.
https://bugs.webkit.org/show_bug.cgi?id=76707

**Comment by jekuno** [comment]
Nice that you found the root cause! 👍
