### ISSUE TITLE
Copy and Paste images between 2 Pencil documents does not work

### ISSUE THREAD

**Issue by rdevall** [evolus/pencil#393]
* Operating system: Windows 7 (same issue on Windows 10)
* Pencil version: 3.0.4

With 2 instances of Pencil running with separate documents open. 
Paste an image from the clipboard to document 1 and save.
Select the image in document 1 and copy.
Paste selected image into document 2 and save.
The image will show in document 2.
Close ALL open instances of Pencil.
Open document 2.
The image shows as a broken image.

**Comment by dgthanhan** [comment]
This fix will be available in 3.1.2
