### ISSUE TITLE
Can't get app-deps via yaourt install (AUR)

### ISSUE THREAD

**Issue by SecT0uch** [evolus/pencil#397]
* Operating system: Arch Linux x64
* Pencil version: 3.0.4

When installing pencil package from AUR it freezes randomly.
When I clone the repository, run `nmp install` and `npm star`t Pencil works well without any crash.

This is because when I install pencil package from AUR (with yaourt) I don't get the dependencies : 
`npm WARN lifecycle Pencil@~postinstall: cannot run in wd %s %s (wd=%s) Pencil@ install-app-deps /tmp/yaourt-tmp-jordan/aur-pencil/src/pencil-3.0.4`
> NPM tries to downgrade its privileges when it runs scripts. That downgrading the privileges causes this error.

**Comment by prikhi** [comment]
Hey, AUR maintainer here - work is kinda busy so might be a while before I can look into this. Thought I had all the yaourt kinks worked out :/

Does the issue happen if you just use makepkg instead of yaourt?

**Comment by SecT0uch** [comment]
Same problem with `makepkg -Acs`:
`npm WARN lifecycle Pencil@~postinstall: cannot run in wd %s %s (wd=%s) Pencil@ install-app-deps /home/jordan/Apps/cil/pencil/src/pencil-3.0.4`

**Comment by prikhi** [comment]
Pushed a new PKGBUILD that adds `--unsafe-perm` to `npm install`. Seems to fix the issue for me.

**Comment by SecT0uch** [comment]
I confirm, issue fixed. 👍
