### ISSUE TITLE
"Duplicate" missing

### ISSUE THREAD

**Issue by jekuno** [evolus/pencil#40]
* Operating system: Mac OSX
* Pencil version: 3.0.0-beta2

I can't find any context menu entry to duplicate items (e.g. text fields, buttons or labels). Is this a bug or isn't there any feature like this yet and I need to copy + paste manually?

**Comment by mbrainiac** [comment]
Hi @jekuno 

Use SHIFT + Drag to duplicate shapes

**Comment by jekuno** [comment]
Ah, thanks for this.

Maybe it would be a good idea to also add a context menu entry and/or a toolbar button next to the copy/paste buttons for newbies like me?!

**Comment by mtancoigne** [comment]
This behavior is a bit dangerous, or it should have a kind of _mouse resistance_, my testing drawing is full of duplicates because of small 1-2 pixels shift+drags (small mistake from me as i'm messing with ctrl/shift for multiple select).

With a _mouse resistance_, user would know he's going to duplicate the selection...

**Comment by larvanitis** [comment]
Indeed, I usually shift-drag to skip grid snapping and end up with duplicates all over the place.

I would prefer the menu option in addition to Ctrl-D shortcut. I don't think duplication is used that often to hold such a useful mouse shortcut (Shift+drag).

**Comment by pnvananh** [comment]
Hold Shift before dragging to duplicate shapes. Holding it after a drag is started to prevent snapping.

**Comment by jekuno** [comment]
From a users perspective:

- I think most users look for a toolbar button and a (context) menu entry to duplicate items. (as they don't know about this "hidden" Shift+Drag feature)
- Additionally it might be helpful to assign the key combination Ctrl+D (CMD+D on Mac) to the duplicate action as well as this is the default key combination for duplication in most programs.
