### ISSUE TITLE
Oval Yellow Handle Error

### ISSUE THREAD

**Issue by july8six** [evolus/pencil#408]
* Operating system: CentOS 7
* Pencil version: 3.0.4

Yellow handle on oval does not change shape of oval when moved.  The oval is located under the common shapes collection.
![oval error 1](https://user-images.githubusercontent.com/25120995/30624312-86955dca-9d71-11e7-9274-8986016c43fb.png)

![oval error 2](https://user-images.githubusercontent.com/25120995/30624316-8a737db4-9d71-11e7-903d-9ae7bc2ef1da.png)

**Comment by dgthanhan** [comment]
The handle is for configuring the padding arround text inside that shape, if any.

**Comment by july8six** [comment]
Thanks for letting me know.  It works.
