### ISSUE TITLE
Sizing Policy does nothing

### ISSUE THREAD

**Issue by ghost** [evolus/pencil#433]
* Operating system: Window 10
* Pencil version: 3.0.4
Imported a rectangular image, want to resize, ignoring aspect ratio (Make it wider without making it taller) and the sizing policy option do absolutely nothing as far as I can tell and none of the options in the sizing policy window have any description of what they actually do. I don't know what those icons are trying to communicate.

**Comment by ziegenberg** [comment]
The sizing policy does only apply when:
* the container of an object is moved or resized
**AND**
* the elements are grouped

**Comment by dgthanhan** [comment]
This is working as intended.
