### ISSUE TITLE
Cannot import collections of version 2.0.5 in 3.0.4

### ISSUE THREAD

**Issue by StefanVdMn** [evolus/pencil#457]
* Operating system: Windows 7 Professional
* Pencil version: 3.0.4

I jumped from Pencil 2.0.5 to 3.0.4. Now it seems I cannot import in 3.0.4 the collections I export in 2.0.5?
I get the error "Error Installing collection. Collection specification is not found  in the archive. The file may be corrupted".
The collection exported from 2.0.5 is a ZIP-file containing a Definition.xml file.
[Pencil-e-Cat components.zip](https://github.com/evolus/pencil/files/1555225/Pencil-e-Cat.components.zip)
Any ideas on this? Thank you!

**Comment by StefanVdMn** [comment]
Issue closed, found out how: via "Import new private collection" on the My Shapes tab.

**Comment by koppor** [comment]
@StefanVdMn Could you point me to the button?

I can't find the button "Import new private collection" on the tab "My Shapes":

![grafik](https://user-images.githubusercontent.com/1366654/99313925-a1b69100-2860-11eb-9e4a-eb14bbc13943.png)

I am using Version 3.1.0

**Comment by koppor** [comment]
Found it: lower left corner is the key

![grafik](https://user-images.githubusercontent.com/1366654/99315033-4b4a5200-2862-11eb-85b3-423995cda06e.png)

Then, one can "Install From File..."

![grafik](https://user-images.githubusercontent.com/1366654/99315075-5c935e80-2862-11eb-9377-badeb100f490.png)
