### ISSUE TITLE
Flowchart Multi-segment Connector

### ISSUE THREAD

**Issue by jonpoeschek** [evolus/pencil#47]
* Operating system: Windows 10 Enterprise x64
* Pencil version: 3.0.0-beta.2

The Flowchart Multi-segment connector appears to be broken. When I try to connect two stencils, the end connection does not connect.

![image](https://cloud.githubusercontent.com/assets/19938440/16059303/4bfda48e-3237-11e6-98b7-202ee805e281.png)

**Comment by Kingdutch** [comment]
I would like to confirm this issue with identical behaviour as in the above picture for:
Debian GNU/Linux 8
Pencil 3.0.0-beta.2
