### ISSUE TITLE
Unable to open my pencil file 

### ISSUE THREAD

**Issue by hardik4monto** [evolus/pencil#476]
* Operating system: Win 8.1
* Pencil version: 3.0.4

Suddenly Pencil file size become 0 kb and unable to open pencil file.. 

I got related files from system temp folder which have small thumb images and xml files but don't know how to recover from it. 

Please hep me. 
I am attaching Lotus_wire_frame.epgz and xml files 
[LT-Files.zip](https://github.com/evolus/pencil/files/1750727/LT-Files.zip)

**Comment by dgthanhan** [comment]
Please send me an email at an.duong   -- at --  evolus.vn.
