### ISSUE TITLE
Exporting to PNG file opens folder select dialog instead of file save

### ISSUE THREAD

**Issue by ale-carra** [evolus/pencil#481]
* Operating system: Windows 10 
* Pencil version: 3.0.4

When I try to export a PNG file, instead of a file save dialog I get a folder select dialog. A file save dialog should be displayed instead.

**Comment by dgthanhan** [comment]
@ale-carra How did you perform the action?
There are modes to export the drawing to PNG: either for the whole document or for a specific page.

If you are exporting the whole document, Pencil will ask for a folder not a file even if that document contains just one page. This is the **expected** behavior and not something to fix.

If you only want to export a single page, right click on that page name and select "Export page as PNG...", there you can select the output as a file.

**Comment by ale-carra** [comment]
I performed the action by clicking File>Export then choosing PNG. The file only had one page and exporting to SVG showed a Save File dialog so I expected a Save File dialog for PNG as well. It is not intuitive at all...
