### ISSUE TITLE
Can I build pencil with system electron

### ISSUE THREAD

**Issue by Brli** [evolus/pencil#483]
* Operating system: Arch Linux
* Pencil version: 3.0.4
Is it possible to patch the source for system with electron installed, so that user doesn't need to recompile electron during installation.
If so, could you guide me through this?

**Comment by lewellyn** [comment]
If you're using Arch, why aren't you installing via AUR? (As for system Electron, I'd expect that it'd be done in AUR if it's possible anywhere.)

Looking at the AUR entry, it looks like the package may be slightly broken at the moment, but that's almost certainly an issue that should be taken up with the AUR maintainer as it looks like it may be a dependency issue.

Most systems don't deliver a system-wide Electron by default, so in the generic case, your question isn't very answerable. :(

**Comment by Brli** [comment]
Hi, @prikhi 

Thx for the maintenance of the AUR package.

"It works" as refer to the compiling and packaging.

But what I'm asking here is about "not to re-compile the whole Electron chain" as the system has one already, and the build would definitely reduced both in size and in time if we wouldn't need to recompile the whole Chromium thing to just have the codes in place (if not in binary form).

**Comment by dgthanhan** [comment]
@Brli 
Pencil 3 has many critical parts that depend on Electron and due to the fact that Electron API used to have breaking changes in new releases, it is not easy to ensure reliable working status of Pencil on a wide range of Electron versions. This is the major reason we don't recommend creating Pencil builds that use system-provided Electron runtime.

**Comment by prikhi** [comment]
> But what I'm asking here is about "not to re-compile the whole Electron chain" as the system has one already

@Brli Yeah I get that, I was simply responding to this bit:

> Looking at the AUR entry, it looks like the package may be slightly broken at the moment

I'm guessing you've already tried the `evolus-pencil-bin` package?

**Comment by Brli** [comment]
I managed to workaround `package.json` and `app/package.json` to escape the compilation of electron in AUR, now that the software works with electron9 nicely.

Please consider an update to electron dependency as it seems a bit outdated.

**Comment by dgthanhan** [comment]
The primary dev code branch for Pencil is 'development' not the 'master'. Dev code branch has Electron upgraded to 10 about a week ago.
