### ISSUE TITLE
When using the "Table" element from "Desktop - Sketchy GUI" other element are not selectable

### ISSUE THREAD

**Issue by skamlet** [evolus/pencil#49]
Put a Combobox on your page and then put a Table.
If you resize this Table, the Combobox is no more selectable.

* Operating system: Windows 7
* Pencil version: 3.0.0-beta.2

**Comment by viktor-zin** [comment]
Objects which are above the table and on the left of its side are not able to be selected. OS - Win7 x64, Pencil - beta2.

**Comment by soitech** [comment]
Mac OSX 10.11 3.0.0-Beta.2

Had page with table, dropped in combobox and cannot select combobox to move, resize, edit.

**Comment by godly-devotion** [comment]
Why was this issue closed? I can still reproduce the issue on Windows 10 running beta 2.

**Comment by viktor-zin** [comment]
I think it was fixed, but a new release is not ready. Probably we'll see the next beta with the fixed problem. Let's wait for the next release.
