### ISSUE TITLE
Menu text & Icons rendering issue

### ISSUE THREAD

**Issue by hubitor** [evolus/pencil#511]
Menu text and icons are not rendered properly and text is partially overlapping. Looks like this:

![pencil_screenshot_20180703_123744](https://user-images.githubusercontent.com/6114541/42215441-bb8034ea-7ebe-11e8-8891-2cb0f80fd626.png)

* Operating system: Arch Linux
* Pencil version: 3.0.4

**Comment by minthemiddle** [comment]
Also happening on Mac High Sierra, Pencil 3.0.4.

![screen shot 2018-09-16 at 14 03 20](https://user-images.githubusercontent.com/1950766/45596242-4acf7b80-b9b9-11e8-99e7-73734806ef76.png)

**Comment by dgthanhan** [comment]
This is fixed in the latest development code and available in [nighly builds](http://pencil.evolus.vn/Nightly.html)
