### ISSUE TITLE
Can open my file (file corrupt)

### ISSUE THREAD

**Issue by rztprog** [evolus/pencil#526]
* Operating system: Ubuntu (Linux)
* Pencil version: 3.0.4

my file & entire of my pencil software was corrupted, i tried to reinstal pencil/nighlty/stable it dosnt work

i upload my file to https://mega.nz/#!WmRw0SaC!wNX82iuPFovALPw8DXFHT-wZMv5mCmRe0hfvHeSj5hg

ty in advance

**Comment by dgthanhan** [comment]
@rztprog is this your email address? rztprog*at*o u t l o o k .fr

**Comment by rztprog** [comment]
@dgthanhan Yes ! :)
