### ISSUE TITLE
Goes blank after a flash showing the content

### ISSUE THREAD

**Issue by zenny** [evolus/pencil#53]
* Operating system: Ubuntu Linux 14.04.4 LTS
* Pencil version: 3.* beta

Installed 3Beta version from .deb package with gdebi to ensure all dependencies are installed. Pencil opened alright by default, but when more plugins like bootstrap were installed, the application shows a flash of the app and then goes completely blank, thus preventing to do anything!

> $ /opt/Pencil/Pencil --help
> Hardware acceleration disabled for Linux.
> Platform: linux
> Background web-printer started.
> RENDERER started.

**Comment by dgthanhan** [comment]
This is a duplication of #35.
