### ISSUE TITLE
Please made a new release

### ISSUE THREAD

**Issue by Mannshoch** [evolus/pencil#531]
The last Release is from 2017

**Comment by frank-dspeed** [comment]
@Mannshoch Please clos this issue and think twice if this is a chat or development. I can Understand your point but this is opensource that sayed you can make the next release happen more fast when you close this.

**Comment by Mannshoch** [comment]
Thanks for reminding me to think twice. I did it and agreed with what I was doing. 
Your point is correct and I'll try helping release faster. 
I Close this Issue.
