### ISSUE TITLE
web server download fail

### ISSUE THREAD

**Issue by v-osnovnom-bezvreden** [evolus/pencil#536]
This problem is not directly related  to the software, but I suppose  it is important, so I report it here.

At the moment it is impossible to download any of the files from https://pencil.evolus.vn/Downloads.html
Shortly after download start error "failed - file incomplete" appears. 
Problem persists in all browsers.

**Comment by petrgon** [comment]
You can download it from here https://filehippo.com/download_pencil/ meanwhile. I already validated checksum, so it is ok. But I advise you to validate your downloaded file too.

**Comment by dgthanhan** [comment]
We solved the storage problem in our server. This is hopefully OK now.

**Comment by v-osnovnom-bezvreden** [comment]
@dgthanhan I confirm problem is solved. I was able to download and install. Cant wait to use it :)  Thanks a lot for quick reaction! Issue can be closed now.
