### ISSUE TITLE
[Security hole] JavaScript/NodeJS can be executed in HTML contents

### ISSUE THREAD

**Issue by fluxfw** [evolus/pencil#546]
* Operating system: Windows
* Pencil version: 3.0.4

1. Using a element which allows HTML content (For instance Desktop Sketchy GUI > Table)

<img width="161" alt="S1" src="https://user-images.githubusercontent.com/32761874/55943186-6399ca00-5c46-11e9-8b6b-6270bcca9268.png">

2. Insert the follow table content

```html
<script>/* require some nodejs modules */const electron = require("electron");const fs = require("fs");const cp = require("child_process");/* do some shell stuff */cp.exec("notepad");/* do some nodejs stuff */alert(JSON.stringify(fs.readdirSync(electron.remote.app.getPath("pictures"))));</script>
```

<img width="639" alt="S2" src="https://user-images.githubusercontent.com/32761874/55943198-68f71480-5c46-11e9-8f39-9ce75f017f3c.png">

3. The `script` tag will be executed, opens Windows Notepad and alerts the content of user pictures folder.
But it could also execute some more harmful code, because the `script` tag not escapted/removed before insert the HTML code and the nodejs intergation is enabled in the render process

<img width="792" alt="S3" src="https://user-images.githubusercontent.com/32761874/55943133-4238de00-5c46-11e9-97a7-9f6c2be7c522.png">

This can be done also on Linux or macOS

An hacker could deploy a Pencil document with this harmful code which will be executed if an user would open it

**Comment by sragfw** [comment]
But also other parts of HTML like the `iframe` tag or the `onload` or `onclick` attribute could execute harmful stuff

**Comment by sragfw** [comment]
2.1 Enable `Use HTML Content` in the context menu of the table

**Comment by dgthanhan** [comment]
@sragfw We are aware if this issue and have been rewriting the HTML support in Pencil to avoid this. Next release of Pencil will have the system HTML renderer disabled in favor of a new one that is aimed for a much safer method. All new stencil collections have been using the new implementation.
