### ISSUE TITLE
Hardware acceleration disabled for Linux

### ISSUE THREAD

**Issue by aleksandaratanasov** [evolus/pencil#55]
* Operating system: Debian Jessie 64bit
* Pencil version: 3.0.0 beta 2

May I ask which part of Pencil uses hardware acceleration and also if support for it on Linux platforms is planned for the future?

**Comment by dgthanhan** [comment]
Linux builds of Pencil currently has hardware acceleration disabled entirely by default. We encountered dramatic performance degradation when running on Linux with HA on in most of our test machines.

Option to enable HA on Linux will be added in the next release after 3.0.0.

**Comment by aleksandaratanasov** [comment]
Thanks for the heads up!

PS: I love what the Pencil team has done with the application. I've lost hope in seeing a new version but then today I decided to check the website and - wow! - there it was. :) I hope the exporting features work now. :P

**Comment by sgon00** [comment]
Hi, I am running pencil 3.0.4-1 and archlinux. This issue has been closed for more than a year. But I still see `Hardware acceleration disabled for Linux` in the latest version. Any updates on this? Thanks a lot.

**Comment by kokmok** [comment]
I think they need time or hands to code this. The last commit is from 2017.

Anyway, you can clone the repo. Go to the app/index.js file and comment thoses lines :
```
if (process.platform.trim().toLowerCase() == "linux" && app.disableHardwareAcceleration) {
    console.log("Hardware acceleration disabled for Linux.");
    app.disableHardwareAcceleration();
}
```

**Comment by overtube** [comment]
> I think they need time or helpful hands to code this. The last commit is from 2017.
> 
> Anyway, you can clone the repo. Go to the app/index.js file and comment thoses lines :
> 
> ```
> if (process.platform.trim().toLowerCase() == "linux" && app.disableHardwareAcceleration) {
>     console.log("Hardware acceleration disabled for Linux.");
>     app.disableHardwareAcceleration();
> }
> ```
> 
> It solves the issue for me

great, but what I need to do if I want install these for archlinux using pkgbuild
