### ISSUE TITLE
Segmentation Fault in Arch Linux

### ISSUE THREAD

**Issue by prikhi** [evolus/pencil#560]
* Operating system: Arch Linux - up to date as of 8/15/2019
* Pencil version: v3.0.4

Running pencil in an up to date Arch Linux causes the program to immediately crash with a segmentation fault.

Running pencil with `node_modules/.bin/electron app/index.js` gives a stacktrace:

```
Hardware acceleration disabled for Linux.
Background web-printer started.
/tmp/makepkg/pencil/src/pencil-3.0.4/node_modules/electron/dist/electron[29929]: ../../vendor/node/src/async-wrap.cc:357:void node::SetupHooks(const FunctionCallbackInfo<v8::Value> &): Assertion `env->async_hooks_init_function().IsEmpty()' failed.
 1: node::Abort() [/tmp/makepkg/pencil/src/pencil-3.0.4/node_modules/electron/dist/libnode.so]
 2: 0x7ff624516cf4 [/tmp/makepkg/pencil/src/pencil-3.0.4/node_modules/electron/dist/libnode.so]
 3: 0x7ff624501025 [/tmp/makepkg/pencil/src/pencil-3.0.4/node_modules/electron/dist/libnode.so]
 4: 0x7ff623dfbbba [/tmp/makepkg/pencil/src/pencil-3.0.4/node_modules/electron/dist/libnode.so]
 5: 0x7ff623cef662 [/tmp/makepkg/pencil/src/pencil-3.0.4/node_modules/electron/dist/libnode.so]
 6: 0x7ff623ceed74 [/tmp/makepkg/pencil/src/pencil-3.0.4/node_modules/electron/dist/libnode.so]
 7: 0x2e879420463d
```

Some searching led me to this issue:
https://github.com/electron/electron/issues/10905#issuecomment-385734327

The suggested fix is to replace `unzip2` with `unzipper`, which is a drop-in replacement. After doing this, pencil was still crashing but this time without an error message.

To fix that, I incrementally upgraded the `electron` dependency & retested. I ended up needing to install v1.8. Afterwards, I'm able to run Pencil without crashing.

I will submit a PR with my fix.

**Comment by dgthanhan** [comment]
@prikhi This is fixed in the latest development build. This is also using the 6.0.1 electron too. Please try the [Nightly builds](http://pencil.evolus.vn/Nightly.html)

**Comment by prikhi** [comment]
Awesome, thanks for the quick response. I'm on archlinux, so I built it from the `development` branch and it works.
