### ISSUE TITLE
Pencil does not start

### ISSUE THREAD

**Issue by hubitor** [evolus/pencil#568]
* Operating system: Arch Linux
* Pencil version: 3.0.5 (development branch: 1489.848f674)

I had an issue with v3.0.4 stable version which is fixed in the development branch:
[https://github.com/evolus/pencil/issues/511](url)

I've installed the latest version of the development branch and now when I try to start Pencil a window with a white background opens and the Pencil logo in the middle   blinking the whole time.

I tried to open Pencil from the terminal but I see no error:
```
$ pencil.sh
Hardware acceleration disabled for Linux.
Background web-printer started.
```

I've renamed the Pencil folders within my home folder and within the .config folder but it didn't help.

**Comment by yanickrochon** [comment]
This is the error I see :

```
$ pencil 
pencil: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
```

It seems like the dependency on GTK is outdated?

**Comment by jmtb28** [comment]
One workaround that I did is to replace `Exec=/opt/pencil-3.1.0.ga/pencil` with `Exec="/opt/pencil-3.1.0.ga/pencil" --no-sandbox %U` in `/usr/share/applications/pencil.desktop`.

OS: Debian 10
Pencil version: 3.1.0

**Comment by hubitor** [comment]
In:
`/usr/share/applications/pencil.desktop`
there is:
`Exec="/usr/bin/pencil.sh" `
and 
`--no-sandbox %U`
didn't help.

I've installed the latest version (3.1) and both issues I had are fixed.
