### ISSUE TITLE
Add Tag or Github Release for v3.1.0

### ISSUE THREAD

**Issue by prikhi** [evolus/pencil#575]
I see v3.1.0 was release yesterday. For updating the archlinux builds, it'd be good if we could have a tag or github release so I can ensure the v3.1.0 code is downloaded & not just whatever happens to be on master at the moment. 

Thanks!

**Comment by dgthanhan** [comment]
@prikhi Thanks for the reminder!
The tag is created at [https://github.com/evolus/pencil/tree/v3.1.0](https://github.com/evolus/pencil/tree/v3.1.0)

**Comment by prikhi** [comment]
Thanks for the quick turnaround! The last thing I need to make new packages is in #576.

While testing those changes, I noticed that the `npm run dist:osx` is broken as well, it seems like upgrading `electron-builder` to `20.31.3` will fix this but I'm waiting for the build to finish so I can confirm that: https://github.com/electron-userland/electron-builder/issues/3385#issuecomment-454293865
