### ISSUE TITLE
[BR] v3.1.0 break search bar

### ISSUE THREAD

**Issue by kopax** [evolus/pencil#577]
Since `v3.1.0`, it is not possible to use the search bar, every research return an empty result

* Operating system: Debian 10
* Pencil version: 3.1.0

Related PR: https://github.com/evolus/pencil/pull/573

**Comment by kopax** [comment]
How can I download `.deb` for v3.0.4 please ?

**Comment by dgthanhan** [comment]
[Nightly Builds](http://pencil.evolus.vn/Nightly.html) should contain this fix now.
