### ISSUE TITLE
Please provide a "self contained" installation for Linux (without Sudo)

### ISSUE THREAD

**Issue by aoloe** [evolus/pencil#588]
Currently I need to be root (sudo) for installing and running Pencil.

This is true for both the deb / rpm (I guess... haven't tried) and the `setup.sh` (tries to put things in (`/opt` and `/usr/share`).

On top of it, I seem to need to to run `chrome-sandbox` as root, otherwise I get the error:

"The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that chrome-sandbox is owned by root and has mode 4755."

There are a few problems with that:

- Personally, I will not run as root any software (install script included) that I download from the internet.
- No software I download should touch `/usr/` (except, for  `/usr/local/`)
- I don't trust `.deb` packages that are not _good enough_ to be integrated in the Debian (or Ubuntu) repositories.

I have a Pencil 3.0 that runs from `~/bin/pencil/pencil`, with no special rights, it would be nice to have the same "comfort" for Pencil 3.1.

There are a few action you can take:

- get Pencil to be included in the Debian (and Ubuntu) repositories.
- make sure that Pencil does run as a _normal_ user from the user's home directory.
- provide an Appimage.

**Comment by dgthanhan** [comment]
@aoloe Have you tried the tar.gz nightly build package here?
http://pencil.evolus.vn/Nightly.html

**Comment by aoloe** [comment]
@dgthanhan yes, since i don't install _foreign_ `.deb`s, i did try with the nightly `tar.gz`:

- the setup process needs sudo.
- it installs things all over my hard disk (`/opt/` and `/usr/share` + some other places iirc).
- if if don't install it, and try to run `pencil.sh`, i get the `chrome-sandbox` error mentioned above. the error would have probably also happened, if i would have have used the setup script to install Pencil. (from what i've read in the setup script, there is nothing really important for Pencil in there.)

this is from my memories, since i've deleted the files and i can't find the setup script on github.

i could not find a link to the `tar.gz` for the released 3.1.

**Comment by caissalover** [comment]
Why does a software need to be run as root ever?! This is strange. Please fix this ASAP.

**Comment by dgthanhan** [comment]
Pencil is using Electron as the runtime and the suid things come from the electron itself. We are not officially providing a package for Debian.
See also this discussion thread for more details.
https://unix.stackexchange.com/questions/538709/i-cant-execute-electron-in-debian-10
A contribution for making it usable on Debian is much appreciated.

**Comment by aoloe** [comment]
i had forgot this ticket...

i had a look at it again and did an internet search. the result:

starting pencit as `./pencil --no-sandbox` does work.

i leave it here as a workaround, for those who would stumble on this ticket in the future.

personally, i cannot really tell if it's a good idea to remove the sandboxing, but at first sight it looks better than adding any sudo capabilities to keep around a sandboxing from where the program needs to break out by being sudo (if i got correctly what is happening).

there is a ticket in the electron project but i did not really understand the  reason why it has been closed:

https://github.com/electron/electron/issues/17972

... there might or not be a real solution to this issue... i don't know. maybe somebody else can enlighten me.
