### ISSUE TITLE
No copy+paste ?

### ISSUE THREAD

**Issue by jnicolau** [evolus/pencil#59]
* Operating system: MacOS
* Pencil version: 3

It's not possible to copy paste anything.

**Comment by liamdawson** [comment]
I have no issues on Windows 10 x64. By the way, which way(s) did you try to copy and paste with?

**Comment by claudiowagner** [comment]
Same problem on MacOS.

Command-C and Command-V in a propertie value (like color) not work.

**Comment by liamdawson** [comment]
I'm guessing this is a "CommandAndControl" issue - Electron has a specific keybinding to choose command if on OSX, control otherwise. Have you tried Ctrl+C/V, just for more information? Might be a simple fix if that works. (or at least clear enough for someone to PR?)

**Comment by dgthanhan** [comment]
If you problem is at copying in the 'Properties' side pane, it is already fixed and will be available in the next build.

And no, it's not any related to the Cmd&Ctrl issue. We are not using Electron-specific keybinding. Thanks for the hint anyway.
