### ISSUE TITLE
Button links do not work when a page is set as a background

### ISSUE THREAD

**Issue by miniragnarok** [evolus/pencil#60]
When mocking a website, I would like to create a background page that acts as the navigation. An easy way to do that is to create some buttons, right-click, hover over Link To, and finally select the page it links to. I'm then using that page as a background for all of the other pages. The problem is that when I export the project as a single web page, the only page that the links work on is the background page.

I've verified that this used to work on the previous version of Pencil. I've tried creating a new project as well as opening a project from version 2.* and neither work. The version 3 will strip the links that worked in version 2.

* Operating system: Windows 7
* Pencil version: 3.0.0-beta.2

**Comment by larvanitis** [comment]
To me it looks like the "Background Page" is used as a screenshot. For example set a bg page and zoom in to see it pixelated.

Is this a design choice?

**Comment by miniragnarok** [comment]
I'm not sure I understand the question. Is what a design choice?

It's fine that it creates a screenshot. As near as I can tell it always did that. However, it used to create links too. 

I'm not opposed to achieving this in a different way but as near as I can tell this is a bug. There simply is no way to create links once and use them everywhere anymore. 

Pencil version 2
![pencilmock1](https://cloud.githubusercontent.com/assets/5341354/17530108/1e1a2c16-5e44-11e6-8576-514146e907dd.png)

Pencil version 3
![pencilmock2](https://cloud.githubusercontent.com/assets/5341354/17530122/3078ad7e-5e44-11e6-88ad-2ec1f47cc5ac.png)

**Comment by larvanitis** [comment]
From your screenshots I can see that the image map is missing in v3.

So to be be more specific, was the removal of the image map a design choice or is it simply a bug?

**Comment by miniragnarok** [comment]
Gotcha. 

I thought you were asking me if something was a design choice and that wasn't making any sense to me. Thanks! :)

**Comment by miniragnarok** [comment]
Why is this closed? I can't fathom that you'd make a mocking tool and have no way of creating navigation once and have it populate the other mocks.

**Comment by dgthanhan** [comment]
Because of this one: 7ea2ed75f34e0ac6d9de40bc9ef9efcc7bda3b34
The dev simply forgot to include the fix in the comment. Please check the activity before posting.

**Comment by miniragnarok** [comment]
Thanks. 

Btw, I did check the commits and releases and didn't see anything recently. I don't use git or github though so I'll admit I don't know how this works.

Thanks again!
