### ISSUE TITLE
Scrolling the properties of objects

### ISSUE THREAD

**Issue by ss-12** [evolus/pencil#603]
* Operating system: Windows 10
* Pencil version: 3.1.0
Some options are out of screen after right click on any objects, and scrolling up or down into it is not possible.
![Screenshot (7)](https://user-images.githubusercontent.com/60283701/73117432-96117b00-3f6b-11ea-949d-1c8fa6099799.png)

**Comment by dgthanhan** [comment]
The fix for this will be available in 3.1.2.
