### ISSUE TITLE
Export single web page width/height is NaN

### ISSUE THREAD

**Issue by dwatow** [evolus/pencil#604]
* Operating system: macOS Mojave 10.14.6
* Pencil version: 3.0.1

because width/height is NaN, every link not match the position.

export result:

![image](https://user-images.githubusercontent.com/1825852/73899985-369b5f80-48c9-11ea-8179-4fef1b3c9634.png)

source code:

**pencil/app/pencil-core/templates/HTML/default.HTML/StyleSheet.xslt**
```
                <img src="{@rasterized}"
                    width="{p:Properties/p:Property[@name='width']/text() * p:Properties/p:Property[@name='bitmapScale']/text()}"
                    height="{p:Properties/p:Property[@name='height']/text() * p:Properties/p:Property[@name='bitmapScale']/text()}"
                    usemap="#map_{p:Properties/p:Property[@name='fid']/text()}"/>
```

**Comment by swiftech** [comment]
So, any workaround for this issue?

**Comment by dwatow** [comment]
#610 
#713
