### ISSUE TITLE
Provide a Flatpak package

### ISSUE THREAD

**Issue by yosbelms** [evolus/pencil#617]
Could be nice to have a Flatpak bundle available in Flathub.

**Comment by digitalethics** [comment]
Providing only .deb or .rpm packages is out of sync with how applications are installed on modern Linux-based systems nowadays. First of all, it is extremely troublesome to package the applications in these two distribution formats and it _unjustly_ prioritizes some distributions over others (in this case Debian/Ubuntu and Fedora/openSUSE). Applications are not meant to be downloaded and installed manually but in fact, to be distributed in an automated and security-enhanced way via distribution repositories. The current way is _unsafe by design_ as most users would probably not validate their downloads manually. The best way forward in my view is to only provide source tarballs for distribution maintainers to package it up for their users and to additionally adopt both Flatpak and Snap as universal package formats. The latter two users can install in lieu of the version they'd get via their distribution repository (if they wish to do so for testing or sandboxing purposes) or provide an easily accessible way for those who do either not want or can build from source, and when Pencil is not available via their preferred distribution repository. Long story short, I hope Flatpak distribution is prioritized and .rpm and .deb dropped instead.

**Comment by martinandersen3d** [comment]
Looks like **Github Actions** can do that?
https://github.com/marketplace/actions/flatpak-builder

**Comment by yosbelms** [comment]
@dgthanhan Why this issue was closed?
