### ISSUE TITLE
Can't select shapes from the shapes menu

### ISSUE THREAD

**Issue by dlahman** [evolus/pencil#623]
* Operating system: Linux Mint 19.3 
* Pencil version: 3.1.0

**Steps to reproduce:** 
1. Download / Install Pencil Project 3.1.0.ga x64 .deb
2. Open Pencil Project
3. Create new document
4. Open the "Shapes > Common Shapes" menu on the left
5. Click any of the shapes (e.g. Rectangle, Oval, Line, Rich Text, etc.)
6. Attempt to draw/create the shapes in the main window. 

**EXPECTATION:** Selecting the shape on the left would allow me to create those shapes within the canvas.

**REALITY:** None of the shapes could be selected (or created). 

Sidenote: It's possible to click+drag the shapes onto the canvas - but selecting and creating with the mouse doesn't work.

**Comment by Jeff-Haas** [comment]
That's how the UI works - drag a shape or other element onto the work area.  It's not like a paint program where you select an element and then draw it.
