### ISSUE TITLE
installation issue on ubuntu 18.04

### ISSUE THREAD

**Issue by myounus96** [evolus/pencil#648]
* Operating system: ubuntu 18.04
* Pencil version: Latest (.deb downloaded from site)
error
![image](https://user-images.githubusercontent.com/13608139/92020453-9085da00-ed71-11ea-8d58-b78d81f82a83.png)

**Comment by myounus96** [comment]
Nighlty build also giving error.

**Comment by myounus96** [comment]
@dgthanhan is this project active..? Can anyone respond..?

**Comment by buithehoa** [comment]
@myounus96 Showing the full log would help.

**Comment by myounus96** [comment]
> @myounus96 Showing the full log would help.
Please check.
![image](https://user-images.githubusercontent.com/13608139/93165980-e3c73780-f736-11ea-8d7d-23bf4be920e2.png)

**Comment by myounus96** [comment]
@buithehoa ??

**Comment by buithehoa** [comment]
@myounus96 I would start with resolving the first error: `internal gzip read error`. See some suggestion here
https://askubuntu.com/questions/138374/internal-gzip-read-error

And don't be pushy. We do this for free for you.

**Comment by myounus96** [comment]
> @myounus96 I would start with resolving the first error: `internal gzip read error`. See some suggestion here
> https://askubuntu.com/questions/138374/internal-gzip-read-error
> 
> Another option is to give [this nightly build](https://pencil.evolus.vn/dl/development/Pencil-3.1.0.20200915003003.tar.gz) a try.
> 
> And don't be pushy. We do this for free for you.

No success :( .

**Comment by myounus96** [comment]
> @myounus96 I would start with resolving the first error: `internal gzip read error`. See some suggestion here
> https://askubuntu.com/questions/138374/internal-gzip-read-error
> 
> Another option is to give [this nightly build](https://pencil.evolus.vn/dl/development/Pencil-3.1.0.20200915003003.tar.gz) a try.
> 
> And don't be pushy. We do this for free for you.

Let me check nightly build.

**Comment by myounus96** [comment]
Downloading .deb from here https://pencil.evolus.vn/Nightly.html

**Comment by myounus96** [comment]
Latest Stable release .deb 64 is also working fine now.Thanks
