### ISSUE TITLE
Document opening doesnt work

### ISSUE THREAD

**Issue by cochces** [evolus/pencil#66]
* Operating system: Windows 10
* Pencil version: 2.05 a 3.0.0 beta2

Critical bug. I am not able to open saved files correctly. Almost all items are gone. Good project but poor execution.

**Comment by dgthanhan** [comment]
I'm closing this issue as the wording is not appropriate. We expect constructive contribution, otherwise issues will be dismissed.

If you really want to report an issue: describe your issue carefully, attaching files that can help developers reproduce the bug and be polite.

**Comment by cochces** [comment]
This issue is so stupid, that it doesn't need any other description. I am trying to help you with this shit. See attached pictures. File saved in version 205. Same file opened in version 205 and 300 beta. Source file uploaded as zip. Is it now enough constructive? 
 
[test2.zip](https://github.com/evolus/pencil/files/381052/test2.zip)
![test2_opened_3beta](https://cloud.githubusercontent.com/assets/20600319/17095176/77d427fe-5253-11e6-8335-cb26fae84448.png)
![test2_opened_205](https://cloud.githubusercontent.com/assets/20600319/17095177/77d459a4-5253-11e6-992e-41e96f211ec6.png)
![test2_saved_205](https://cloud.githubusercontent.com/assets/20600319/17095178/77d476aa-5253-11e6-9139-615b5402fb33.png)

**Comment by dgthanhan** [comment]
We no longer support the native UI stencils that is something the new implementation is not able to render. Even if the approach is to stick to the old framework, native UI stencils will be soon deprecated.
