### ISSUE TITLE
Export/import

### ISSUE THREAD

**Issue by bsikander** [evolus/pencil#666]
* Operating system: Mac
* Pencil version: 3.1.0

I have made a few diagrams and I would like to share them with the team. I want the team to be able to import these diagrams in their own installation of Pencil. Somehow I am unable to do it. I can only export SVGs/PNGs but not raw/pencil format that can be easily imported.

How to achieve this?

**Comment by netalex** [comment]
why don't you just use te file saved by pencil?

**Comment by bsikander** [comment]
Doing a Save As and importing the same file works. I somehow missed it.
