### ISSUE TITLE
Crashes / Does not Open on Pop OS 22.04 LTS 

### ISSUE THREAD

**Issue by therealayayron** [evolus/pencil#722]
* Operating system:  Pop OS 22.04 LTS
* Pencil version: 3.1.0.ga_amd64.deb  / Latest version

Application does not open and crashes. Icon on OS shows it is opening and the gray screen with part of them is showing but then it closes down.

**Comment by lonewanderer27** [comment]
There is a fix as shown in this issued patch #720 by adding a launch flag:

pencil --disable-seccomp-filter-sandbox

**Comment by therealayayron** [comment]
Is this done bu typing it into the command line?

**Comment by lonewanderer27** [comment]
> Is this done by typing the above into the command line?

yes, 
you can also add the flags using Menu Editor if you have Pencil installed so you don't have to type it in the command line everytime
