### ISSUE TITLE
Does not open / crahses on Fedora 36

### ISSUE THREAD

**Issue by therealayayron** [evolus/pencil#723]
* Operating system: Fedora 36
* Pencil version: 3.1.0.ga_amd64.deb  / Latest version

Application does not open and crashes. Icon on OS shows it is opening and the gray screen with part of them is showing but then it closes down.

**Comment by alienator** [comment]
Hi, the exact error says: pencil project gpu_data_manager_impl_private.cc(894)] The display compositor is frequently crashing. Goodbye.

With --disable-gpu-sandbox works.

**Comment by therealayayron** [comment]
Yes, this works. 

Do we know when this will be amended where we will not have to use the command to correct this?

**Comment by alienator** [comment]
No. but if you don't like to open it by typing the command in the terminal, you can edit the menu launcher. I did it with menulibre available in fedora repos. Just add the options.

**Comment by therealayayron** [comment]
Please note that I have tested this on other Distros and this **_error does not occur_**, without having to edit the menu launcher:

- Fedora Kde Spin 37 (upgraded from Fedora KDE Spin 36) 
- KDE Neon Stable Version

Figured I'd give the Dev's More info on this.

**Comment by alienator** [comment]
Hi, the new version of Pencil (3.1.1) is working fine in fedora 37, no need to modify the launcher as mentioned before.

**Comment by therealayayron** [comment]
I noticed, after reinstalling. 

What is the best way to update application without reinstalling?

**Comment by therealayayron** [comment]
appreciate it. 

I tried using the Ubuntu version of this to update it but it didn't work. Just uninstalled and reinstalled new version. 

I'll close this out as it's solved.
