### ISSUE TITLE
exe file download speed sucks

### ISSUE THREAD

**Issue by openwebkey** [evolus/pencil#767]
* Operating system: win10
* Pencil version: 3.1.1
exe file download speed sucks. Please upload the exe file to the realise section. let's download it from there

**Comment by openwebkey** [comment]
I think there is a problem in the region where I live. When I turned on vpn, I was able to download it immediately

**Comment by Codingale** [comment]
I know this was marked as closed, but I too had this issue. It downloaded at 500 KB/s for most of it, I recommend including an executable with the GitHub releases as their servers have excellent speeds and linking the builds to said release pages or directly.
