### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by gusarg81** [evolus/pencil#793]
Just wanted to know if the project still Alive.

Thanks.

**Comment by loftycamel** [comment]
It may have already stopped. There are too many competitors.

**Comment by jhstatewide** [comment]
@gusarg81 No commits in one year. It's up to you if that meets the qualifications of 'alive' or not.

**Comment by gusarg81** [comment]
> @gusarg81 No commits in one year. It's up to you if that meets the qualifications of 'alive' or not.

Where did you learn to respond so kindly? I would like to learn in the same place! :D
Don't waste your precious keyboard clicks to reply like this in the future...
