### ISSUE TITLE
Improve table and add new table functions

### ISSUE THREAD

**Issue by sebastianfilke** [evolus/pencil#80]
* Operating system: Windows 8.1 and newer
* Pencil version: 3.0.0-rc.1

in the moment this is really a difficult thing. add a function to auto align the column width for the column count. Also add the possibility to set the header size and the text spaces in the properties editor.  furthermore improve the calculation of the spaces between the elements you can see it here. even make it easier to set the table content. is really difficult.
add the possibility to set scrollbars for a table.
add the possibility to fill the content of a table with empty lines and do not update the height of a line if you resize the table

![bild 1](https://cloud.githubusercontent.com/assets/10894484/17355786/635df410-5953-11e6-8ef1-3a18cfbc79e9.png)

**Comment by edrandall** [comment]
I also would like to be able to set column widths.
Perhaps this ticket was closed because the feature already exists?  How?  Documentation?
It's not obvious to a new user.

**Comment by climbatron** [comment]
Thanks erandall, that's what I needed

**Comment by rogerluces** [comment]
Thanks a lot!

**Comment by tyamut** [comment]
The yellow dots don't appear for me on the table. What should I do?
