### ISSUE TITLE
Page notes not persisted

### ISSUE THREAD

**Issue by swiftugandan** [evolus/pencil#81]
* Operating system: Ubuntu
* Pencil version: 3.0.0-rc.1

I created a page note, but after applying it, I cannot find it anywhere ...
Please help

**Comment by ochagnon** [comment]
@ngochicuong why you closed this issue? you fixed it? how? any commit?

I still suffer from that problem, but as you didn't specified how it was fixed, I don't know if I should expect next release to have this bug fixed. or if I need to open a new issue for the same problem

**Comment by HEXcube** [comment]
@ochagnon  I had this issue too. However, after updating to the new `3.0.0 rc2` version released on 09 Feb 2017, this bug doesn't occur anymore! :smiley: So, I guess it's fixed. Why not try the new version yourself? [Link to v3.0.0-rc.2 release](https://github.com/evolus/pencil/releases/tag/v3.0.0-rc.2)
