### ISSUE TITLE
Complex EPZ does not load anymore 

### ISSUE THREAD

**Issue by plaetzchen79** [evolus/pencil#93]
An complex EPZ does not load anymore. When i try to open it in pencil ("Open Document") pencil hangs with high cpu usage and does not load the file. Even after half an hour.
Before i Tried to print the epz file in landscape. Pencil hangs and i killed the process. Possibly this deystroys the epz file. but I am not sure.
Copying and renaming the epz file does not work.
All work gone?
- Operating system: Windows 7
- Pencil version: 3.0. Rc1

**Comment by akachapati** [comment]
Hi, I'm having the exact same issue on a Mac. Any resolution will be greatly appreciated.

**Comment by plaetzchen79** [comment]
There is at least a Workaround. After i unzipped the EPZ file i could see that the there is a  start page pointer to an empty page (i think the one i tried to print) at the top of the epz file. After Setting the pointer to an existing page the Project reloads again.
But my page i tried to print was gone anyway.. But better than nothing

**Comment by nowonderla** [comment]
Hi, I have the same issue, i am using Windows 10. I tried your method to unzip it and i saw the file content.xml and the pointer points to a page that is not loading. I tried opening it in 7zip and edit it but pencil won't load it. I know you have the right method, please tell me how to do it. All my 15 days work is in it. Greatly appreciate if anyone can help me please.

**Comment by nowonderla** [comment]
I solved my problem. Its in here:

https://github.com/evolus/pencil/issues/151

**Comment by plaetzchen79** [comment]
Sorry for not beeing very precise. I couldnt remember what i did exactly. And I think my case was a little different to yours. 
But it is all about correcting the corrupt epz-files. Hope someone can fix the real cause.

**Comment by evatorium** [comment]
The same happened to me. Re-creating archive didn't help. The problem was that one of the pages contained "&" in its name. When browsing the unzipped .epz it appeared that this page was duplicated several times. So the workaround was to remove "&" (namely "&amp;") from all those duplicates and re-archive the file. The content of this exactly page was lost, but all the rest are okay.

**Comment by dgthanhan** [comment]
This is fixed in the latest code. Please wait for the RC2 package build and verify the issue.
